name: "Get Canary Subject"
description: "Gets a name used as the subject of our canary deploy (in the label and tag).  Just the branch name with invalid characters removed."

outputs:
  canary-subject:
    description: "The sanitized branch name to use as canary subject"
    value: ${{ steps.get-subject.outputs.canary-subject }}

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - name: Install tsx
      shell: bash
      run: pnpm add -g tsx

    - name: Run canary subject script
      shell: bash
      id: get-subject
      run: |
        SUBJECT=$(tsx $(dirname $GITHUB_ACTION_PATH)/index.ts)
        echo "canary-subject=$SUBJECT" >> $GITHUB_OUTPUT

    - name: Debug output
      shell: bash
      run: |
        echo "Canary subject from step output: ${{ steps.get-subject.outputs.canary-subject }}"
        echo "Raw output from script execution:"
        tsx $(dirname $GITHUB_ACTION_PATH)/index.ts
