blank_issues_enabled: false
contact_links:
  - name: Get Help - Discord
    url: https://discord.gg/hyperbolic
    about: If you can't get something to work the way you expect, feel free to ask for help in our Discord.
