// prettier-ignore

// This file is auto-generated by the pnpm codegen:update-models script. Do not edit manually.

const _models = [
  "Qwen/Qwen2.5-72B-Instruct",
  "meta-llama/Llama-3.2-3B-Instruct",
  "Qwen/Qwen2.5-VL-72B-Instruct",
  "FLUX.1-dev",
  "mistralai/Pixtral-12B-2409",
  "StableDiffusion",
  "meta-llama/Meta-Llama-3-70B-Instruct",
  "meta-llama/Meta-Llama-3.1-70B-Instruct",
  "meta-llama/Meta-Llama-3.1-8B-Instruct",
  "Qwen/Qwen2.5-Coder-32B-Instruct",
  "meta-llama/Meta-Llama-3.1-405B-FP8",
  "Qwen/Qwen2.5-VL-7B-Instruct",
  "TTS",
  "meta-llama/Meta-Llama-3.1-405B-Instruct",
  "Qwen/QwQ-32B",
  "deepseek-ai/DeepSeek-V3",
  "Qwen/QwQ-32B-Preview",
  "meta-llama/Llama-3.3-70B-Instruct",
  "NousResearch/Hermes-3-Llama-3.1-70B",
  "meta-llama/Meta-Llama-3.1-405B",
  "deepseek-ai/DeepSeek-R1",
] as const;

export type HyperbolicChatModelId = (typeof _models)[number] | (string & {});
