// prettier-ignore

// This file is auto-generated by the pnpm codegen:update-models script. Do not edit manually.

const _models = [
] as const;

const _imageModels = [
  "StableDiffusion",
  "FLUX.1-dev",
  "Qwen/Qwen2.5-VL-72B-Instruct",
  "Qwen/Qwen2.5-VL-7B-Instruct",
  "mistralai/Pixtral-12B-2409",
] as const;

const _chatModels = [
  "Qwen/Qwen2.5-72B-Instruct",
  "deepseek-ai/DeepSeek-V3",
  "deepseek-ai/DeepSeek-V3-0324",
  "meta-llama/Llama-3.3-70B-Instruct",
  "Qwen/Qwen2.5-Coder-32B-Instruct",
  "meta-llama/Llama-3.2-3B-Instruct",
  "meta-llama/Meta-Llama-3.1-405B-Instruct",
  "meta-llama/Meta-Llama-3.1-70B-Instruct",
  "meta-llama/Meta-Llama-3.1-8B-Instruct",
  "meta-llama/Meta-Llama-3.1-405B",
  "deepseek-ai/DeepSeek-R1",
  "deepseek-ai/DeepSeek-R1-0528",
  "Qwen/QwQ-32B",
  "Qwen/Qwen3-235B-A22B",
  "Qwen/Qwen3-235B-A22B-Instruct-2507",
  "Qwen/Qwen3-Coder-480B-A35B-Instruct",
  "openai/gpt-oss-120b-turbo",
  "openai/gpt-oss-120b",
  "openai/gpt-oss-20b",
  "Qwen/Qwen3-Next-80B-A3B-Instruct",
  "Qwen/Qwen3-Next-80B-A3B-Thinking",
  "Qwen/Qwen2.5-VL-72B-Instruct",
  "Qwen/Qwen2.5-VL-7B-Instruct",
  "mistralai/Pixtral-12B-2409",
] as const;

const _completionModels = [
  "Qwen/Qwen2.5-72B-Instruct",
  "deepseek-ai/DeepSeek-V3",
  "deepseek-ai/DeepSeek-V3-0324",
  "meta-llama/Llama-3.3-70B-Instruct",
  "Qwen/Qwen2.5-Coder-32B-Instruct",
  "meta-llama/Llama-3.2-3B-Instruct",
  "meta-llama/Meta-Llama-3.1-405B-Instruct",
  "meta-llama/Meta-Llama-3.1-70B-Instruct",
  "meta-llama/Meta-Llama-3.1-8B-Instruct",
  "meta-llama/Meta-Llama-3.1-405B",
  "deepseek-ai/DeepSeek-R1",
  "deepseek-ai/DeepSeek-R1-0528",
  "Qwen/QwQ-32B",
  "Qwen/Qwen3-235B-A22B",
  "Qwen/Qwen3-235B-A22B-Instruct-2507",
  "Qwen/Qwen3-Coder-480B-A35B-Instruct",
  "openai/gpt-oss-120b-turbo",
  "openai/gpt-oss-120b",
  "openai/gpt-oss-20b",
  "Qwen/Qwen3-Next-80B-A3B-Instruct",
  "Qwen/Qwen3-Next-80B-A3B-Thinking",
  "Qwen/Qwen2.5-VL-72B-Instruct",
  "Qwen/Qwen2.5-VL-7B-Instruct",
  "mistralai/Pixtral-12B-2409",
] as const;

export type HyperbolicImageModelId = (typeof _imageModels)[number] | (string & {});
export type HyperbolicChatModelId = (typeof _chatModels)[number] | (string & {});
export type HyperbolicCompletionModelId = (typeof _completionModels)[number] | (string & {});
export type HyperbolicModelId = HyperbolicImageModelId | HyperbolicChatModelId | HyperbolicCompletionModelId;
